name: Validate PR Description

on:
  pull_request:
    types:
      - opened
      - edited

    branches:
      - main
      - "stable-*"

jobs:
  validate-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          # Fetch only the latest commit for a shallow clone
          fetch-depth: 1
          
          # Limit checkout to the specific folder containing the action
          # path: .github/actions/validate-pr-description

      - name: Use custom PR validation action
        id: validate
        uses: ./.github/actions/validate_pr_description
        with:
          pr_body: "${{ github.event.pull_request.body }}"

      - name: Test output
        if: always()
        run: echo "Result of validation is  ${{ steps.validate.outputs.status }}"

      - name: Set status
        if: failure()
        run: echo "Validation failed."
