name: Validate PR Description

on:
  pull_request:
    types:
      - opened
      - edited

    branches:
      - main
      - "stable-*"

jobs:
  validate-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Use custom PR validation action
        id: validate
        uses: ./.github/actions/validate_pr_description
        with:
          pr_body: "${{ github.event.pull_request.body }}"

      - name: Test output
        if: always()
        run: echo "Result of validation is  ${{ steps.validate.outputs.status }}"
        

      - name: Set status
        if: failure()
        run: echo "Validation failed."

      - name: Comment on PR if validation fails
        if: ${{ failure() && steps.validate.outcome == 'failure' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context } = require('@actions/github');
            const issueNumber = context.payload.pull_request.number;
            const errors = `${{ steps.validate.outputs.result }}`;  # Ошибки из скрипта

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `### Ошибки проверки описания PR:\n\n${errors}`
            });
