name: Weekly Changelog Update

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at 00:00
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.YDBOT_TOKEN }}

jobs:
  gather-branches:
    runs-on: ubuntu-latest

    outputs:
      branches: ${{ steps.branch-list.outputs.branches }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: List 'main' and 'stable-*' branches
        id: branch-list
        run: |
          BRANCHES=$(git branch -r | grep -E "origin/(main|stable-25(-[0-9]*)*)$" | grep -v HEAD | sed "s/origin\///" | xargs | jq -R -s -c "split(\" \")")
          if [ -z "$BRANCHES" ]; then
            BRANCHES="[]"
          fi
          echo "$BRANCHES" > branches.json
          echo "branches=$BRANCHES" >> "$GITHUB_OUTPUT"

  gather-prs:
    runs-on: ubuntu-latest
    needs: gather-branches
    strategy:
      matrix:
        branch: ${{ fromJson(needs.gather-branches.outputs.branches) }}
    outputs:
      prs: ${{ steps.pr-list.outputs.prs }}
      base_branch: ${{ steps.branch-name.outputs.base_branch }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Pass branch name
        id: branch-name
        run: |
          echo "branch=${{ matrix.branch }}" >> "$GITHUB_OUTPUT"

      - name: Set up date range
        id: date-setup
        run: |
          LAST_WEEK_DATE=$(date -d "7 days ago" '+%Y-%m-%dT%H:%M:%SZ')
          echo "LAST_WEEK_DATE=$LAST_WEEK_DATE" >> $GITHUB_ENV

      - name: Get merged PRs
        id: pr-list
        run: |
          echo "::notice:: branch = ${GITHUB_REF_NAME}, date = $LAST_WEEK_DATE"
          REF_NAME=${{ matrix.branch }}
          PRS=$(gh pr list --state merged --json number,title,baseRefName,mergedAt --jq ".[] | select(.baseRefName == \"${REF_NAME}\" and .mergedAt >= \"$LAST_WEEK_DATE\") | {id: .number}" | jq -c -s ".")

          if [ -z "$PRS" ]; then
            PRS="[]"
          fi
          echo "$PRS" > prs.json
          echo "prs=$PRS" >> "$GITHUB_OUTPUT"

      - name: Debug PR list output
        run: |
          cat prs.json

      - name: Upload PRs JSON
        uses: actions/upload-artifact@v4
        with:
          name: prs-json
          path: prs.json

  update-changelog:
    needs: gather-prs
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get current date
        id: get-date
        shell: bash
        run: echo "suffix=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Update Changelog
        uses: ./.github/actions/update_changelog 
        env:
          GH_TOKEN: ${{ secrets.YDBOT_TOKEN }}
        with:
          pr_data: "${{ needs.gather-prs.outputs.prs }}"
          changelog_path: "./CHANGELOG.md" # RODO: Use the correct path to your CHANGELOG.md file
          base_branch: "${{ needs.branch-name.outputs.base_branch }}"
          suffix: "${{ env.suffix }}"
